[tool.poetry]
name = "pytorch-topological"
version = "0.1.0"
description = ""
authors = ["Bastian Rieck <bastian@rieck.me>"]

[tool.poetry.dependencies]
python = "^3.9"
giotto-tda = "^0.5.1"
torch = "^1.10.0"
giotto-ph = "^0.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
